### PR TITLE
feat: health check endpoint

### PR DESCRIPTION
**Pull request by paulushcgcj**
this feature is to include the healthcheck endpoint for deployment check

- adding healthcheck parameter to enable check
- adding healthcheck endpoint for checking
- adding code to append healthcheck endpoint

### CODE REVIEW

**Comment by paulushcgcj** [comment]
I've included the change only for the deployment check but I don't know if the pen test part will require it or not.

**Review by DerekRoberts — APPROVED** [review]
Good idea!  Thanks.  :)

**Review by DerekRoberts — CHANGES_REQUESTED** [review]
We can do this with one var.  If inputs.health_url is set, then URL=inputs.health_url.  inputs.healthcheck would pretty much be implied by the existence of inputs.health_url.

**Comment by DerekRoberts** [comment]
> I've included the change only for the deployment check but I don't know if the pen test part will require it or not.

That's the right idea!  Pen test requires a proper route and skips deployment verification.  We should probably just have pen test clobber the health check if provided.  I can do that in a later PR if we go that way.

**Comment by paulushcgcj** [comment]
> We can do this with one var. If inputs.health_url is set, then URL=inputs.health_url. inputs.healthcheck would pretty much be implied by the existence of inputs.health_url. Default for inputs.healthcheck wouldn't be set.

Decided to just include the variable during URL generation, as the default value now is empty, it won't change anything unless the parameter is set by the user. What do you think @DerekRoberts ?

**Comment by DerekRoberts** [comment]
> Decided to just include the variable during URL generation, as the default value now is empty, it won't change anything unless the parameter is set by the user. What do you think @DerekRoberts ?

Bingo!  :)

**Review by DerekRoberts — APPROVED** [review]
Appreciated!  :)

**Pull request merged**
